In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_theme()

In [2]:
try:
    import sklearn
    print(sklearn.__version__)
    if (sklearn.__version__ < '1.3.0'): #update for latest scikit-learn version
        !pip install -U --user scikit-learn
except Exception as e:
    !pip install scikit-learn

1.3.0

In [3]:
s22 = pd.read_csv("2022-23 Regular Season - Sheet1.csv")
s22.head()

,Rk,Team,Age,W,L,PW,PL,MOV,SOS,SRS,...,FT/FGA,Unnamed: 22,eFG%.1,TOV%.1,DRB%,FT/FGA.1,Unnamed: 27,Arena,Attend.,Attend./G
0,1.0,Boston Celtics*,27.4,57.0,25.0,57.0,25.0,6.52,-0.15,6.38,...,0.197,NaN,0.528,11.3,78.5,0.180,NaN,TD Garden,"766,240","18,689"
1,2.0,Cleveland Cavaliers*,25.4,51.0,31.0,55.0,27.0,5.38,-0.15,5.23,...,0.206,NaN,0.535,14.4,76.3,0.210,NaN,Rocket Mortgage Fieldhouse,"777,280","18,958"
2,3.0,Philadelphia 76ers*,28.2,54.0,28.0,52.0,30.0,4.32,0.06,4.37,...,0.250,NaN,0.541,13.0,77.2,0.217,NaN,Wells Fargo Center,"839,261","20,470"
3,4.0,Memphis Grizzlies*,24.4,51.0,31.0,51.0,31.0,3.94,-0.34,3.60,...,0.190,NaN,0.526,13.1,75.9,0.206,NaN,FedEx Forum,"707,836","17,264"
4,5.0,Milwaukee Bucks*,29.8,58.0,24.0,50.0,32.0,3.63,-0.02,3.61,...,0.184,NaN,0.52,10.4,77.8,0.175,NaN,Fiserv Forum,"718,786","17,531"